const SPACE_ID = process.env.CONTENTFUL_SPACE_ID;
const ACCESS_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN;
const CORE_CONTENT_TYPE = process.env.CONTENTFUL_CORE_CONTENT_TYPE;
const CORE_FIELD_ID = process.env.CONTENTFUL_CORE_FIELD_ID;
const CRAWLER_BLOG_URL = process.env.CRAWLER_BLOG_URL;
const CRAWLER_VIDEOS_URL = process.env.CRAWLER_VIDEOS_URL;

export {
	SPACE_ID,
	ACCESS_TOKEN,
	CORE_CONTENT_TYPE,
	CORE_FIELD_ID,
	CRAWLER_BLOG_URL,
	CRAWLER_VIDEOS_URL,
};
