const SPACE_ID = process.env.CONTENTFUL_SPACE_ID;
const ACCESS_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN;
const CORE_CONTENT_TYPE = process.env.CONTENTFUL_CORE_CONTENT_TYPE;
const CORE_FIELD_ID = process.env.CONTENTFUL_CORE_FIELD_ID;
const CRAWLER_BLOG_URL = process.env.CRAWLER_BLOG_URL;
const CRAWLER_VIDEOS_URL = process.env.CRAWLER_VIDEOS_URL;
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const SENDGRID_EMAIL_FROM = process.env.SENDGRID_EMAIL_FROM;

export {
	SPACE_ID,
	ACCESS_TOKEN,
	CORE_CONTENT_TYPE,
	CORE_FIELD_ID,
	CRAWLER_BLOG_URL,
	CRAWLER_VIDEOS_URL,
	SENDGRID_API_KEY,
	SENDGRID_EMAIL_FROM,
};
