name: 'Portfolio Cypress E2E'
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node:version: '14'
      - name: Install dependencies
        run: npm install
      - name: Create build
        run: npm run prod
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run preview
