name: 'Healthcheck: Lint, Test, and Build'

on:
  pull_request:
    branches:
      - main
      - v5

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

			- name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      # Step 5: Run tests
      - name: Run tests
        run: npm test

      # Step 6: Build the project
      - name: Build the project
        run: npm run build
