name: 'Healthcheck: Lint | E2E'

on:
  pull_request:
    branches:
      - 'main'
      - 'v5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      # - name: Run ESLint
      # run: npm run lint
      - name: Create build
        run: npm run build
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
