name: 'Healthcheck: Lint | E2E'

on:
  pull_request:
    branches:
      - 'main'
      - 'v5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }} # If you're using GitHub Secrets for security
      CRAWLER_BLOG_URL: ${{ secrets.CRAWLER_BLOG_URL }}
      CRAWLER_VIDEOS_URL: ${{ secrets.CRAWLER_VIDEOS_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Output build result (optional)
        run: echo "Build completed successfully"
