name: 'Portfolio Cypress E2E'

on: [push]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
        env:
          CYPRESS_RECORD_KEY: a5b18600-a3a9-4266-8ea3-e964c23bee2b
